name: CI Pipeline

# Starts when push or pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Pull code from GitHub
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: pip

    # Install requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Tests
    - name: Run Tests with Pytest
      run: |
        pytest -v --maxfail=1

    # Check whether the docker image can be created
    - name: Test Docker Build
      run: |
        docker build -t student-performance:test .